/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "DENM-PDU-Descriptions"
 * 	found in "its_facilities_pdu_all.asn"
 * 	`asn1c -fnative-types -gen-PER`
 */

#ifndef	_SpeedLimitContainer_H_
#define	_SpeedLimitContainer_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SpeedLimit.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SpeedLimitContainer */
typedef struct SpeedLimitContainer {
	SpeedLimit_t	*speedLimit	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SpeedLimitContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SpeedLimitContainer;

#ifdef __cplusplus
}
#endif

#endif	/* _SpeedLimitContainer_H_ */
#include <asn_internal.h>
