/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "DENM-PDU-Descriptions"
 * 	found in "its_facilities_pdu_all.asn"
 * 	`asn1c -fnative-types -gen-PER`
 */

#include "SpeedLimitContainer.h"

static asn_TYPE_member_t asn_MBR_SpeedLimitContainer_1[] = {
	{ ATF_POINTER, 4, offsetof(struct SpeedLimitContainer, speedLimit),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SpeedLimit,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"speedLimit"
		},
	{ ATF_POINTER, 3, offsetof(struct SpeedLimitContainer, startingPointSpeedLimit),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DeltaReferencePosition,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"startingPointSpeedLimit"
		},
	{ ATF_POINTER, 2, offsetof(struct SpeedLimitContainer, endingPointSpeedLimit),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DeltaReferencePosition,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"endingPointSpeedLimit"
		},
	{ ATF_POINTER, 1, offsetof(struct SpeedLimitContainer, trafficDirection),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TrafficDirection,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"trafficDirection"
		},
};
static int asn_MAP_SpeedLimitContainer_oms_1[] = { 0, 1, 2, 3 };
static ber_tlv_tag_t asn_DEF_SpeedLimitContainer_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_SpeedLimitContainer_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* speedLimit at 102 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* startingPointSpeedLimit at 103 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* endingPointSpeedLimit at 104 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* trafficDirection at 105 */
};
static asn_SEQUENCE_specifics_t asn_SPC_SpeedLimitContainer_specs_1 = {
	sizeof(struct SpeedLimitContainer),
	offsetof(struct SpeedLimitContainer, _asn_ctx),
	asn_MAP_SpeedLimitContainer_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_SpeedLimitContainer_oms_1,	/* Optional members */
	4, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SpeedLimitContainer = {
	"SpeedLimitContainer",
	"SpeedLimitContainer",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SpeedLimitContainer_tags_1,
	sizeof(asn_DEF_SpeedLimitContainer_tags_1)
		/sizeof(asn_DEF_SpeedLimitContainer_tags_1[0]), /* 1 */
	asn_DEF_SpeedLimitContainer_tags_1,	/* Same as above */
	sizeof(asn_DEF_SpeedLimitContainer_tags_1)
		/sizeof(asn_DEF_SpeedLimitContainer_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SpeedLimitContainer_1,
	4,	/* Elements count */
	&asn_SPC_SpeedLimitContainer_specs_1	/* Additional specs */
};

